ALTER TABLE branches
    ADD COLUMN address VARCHAR(500) NULL,
    ADD COLUMN phone VARCHAR(64) NULL,
    ADD COLUMN email VARCHAR(255) NULL,
    ADD COLUMN manager_name VARCHAR(255) NULL,
    ADD COLUMN active TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN created_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6);
